version: '3.8'

services:
  api:
    container_name: api
    command: sleep infinity
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
    tty: true 
    