version: '3.8'

services:
  api:
    container_name: api
    command: sleep infinity
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "5000:80"      # For HTTP
      - "5001:443"     # For HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    tty: true 
    